import type { SectorDefinition } from "@/types/sector-momentum";

export const unavailableFundamentals = {
  revenueGrowthYoY: null,
  netIncome: null,
  epsGrowthYoY: null,
  forwardPE: null,
  forwardRevenueGrowth: null,
  grossMargin: null,
  earningsSurprise: "unavailable" as const,
  nextEarningsDate: null,
};

export const unavailableExpectation = {
  socialSearchGrowth: null,
  analystRevision: null,
  relativeMomentum: null,
  fundFlow: null,
  trendingKeywords: [],
  sourceNote: "無料データで自動取得できない項目はunavailableとして表示します。",
};

export function sectorCompany(
  ticker: string,
  name: string,
  marketCapUsd: number | null,
  overrides: Partial<SectorDefinition["companies"][number]> = {},
): SectorDefinition["companies"][number] {
  return {
    ticker,
    name,
    countryCode: "US",
    countryName: "United States",
    region: "us",
    exchange: "US",
    businessSummary: "事業内容はFMPまたは手動メモから補完します。",
    marketCapUsd,
    fundamentals: unavailableFundamentals,
    expectation: unavailableExpectation,
    ...overrides,
  };
}

export const SECTOR_SCORE_WEIGHTS = {
  socialSearchGrowth: 0.3,
  analystRevision: 0.25,
  relativeMomentum: 0.25,
  fundFlow: 0.2,
};

export const sectorDefinitions: SectorDefinition[] = [
  {
    id: "technology",
    name: "Information Technology",
    nameJa: "情報技術",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLK",
    marketCapUsd: null,
    keywords: ["software", "cloud", "enterprise AI"],
    companies: [
      sectorCompany("MSFT", "Microsoft", null),
      sectorCompany("AAPL", "Apple", null),
      sectorCompany("ORCL", "Oracle", null),
    ],
  },
  {
    id: "semiconductors",
    name: "Semiconductors",
    nameJa: "半導体",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "SMH",
    marketCapUsd: null,
    keywords: ["semiconductor", "GPU", "HBM"],
    companies: [
      sectorCompany("NVDA", "NVIDIA", null, {
        expectation: {
          ...unavailableExpectation,
          socialSearchGrowth: 82,
          relativeMomentum: 78,
          trendingKeywords: ["GPU", "AI accelerator", "HBM"],
          sourceNote: "SNS/検索は手動更新。無料自動取得は今後対応予定。",
        },
      }),
      sectorCompany("AVGO", "Broadcom", null),
      sectorCompany("AMD", "Advanced Micro Devices", null),
    ],
  },
  {
    id: "communication-services",
    name: "Communication Services",
    nameJa: "通信サービス",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLC",
    marketCapUsd: null,
    keywords: ["digital ads", "streaming", "platform"],
    companies: [
      sectorCompany("GOOGL", "Alphabet", null),
      sectorCompany("META", "Meta Platforms", null),
      sectorCompany("NFLX", "Netflix", null),
    ],
  },
  {
    id: "consumer-discretionary",
    name: "Consumer Discretionary",
    nameJa: "一般消費財",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLY",
    marketCapUsd: null,
    keywords: ["consumer", "e-commerce", "autos"],
    companies: [
      sectorCompany("AMZN", "Amazon", null),
      sectorCompany("TSLA", "Tesla", null),
      sectorCompany("HD", "Home Depot", null),
    ],
  },
  {
    id: "consumer-staples",
    name: "Consumer Staples",
    nameJa: "生活必需品",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLP",
    marketCapUsd: null,
    keywords: ["staples", "defensive", "household"],
    companies: [
      sectorCompany("WMT", "Walmart", null),
      sectorCompany("COST", "Costco", null),
      sectorCompany("PG", "Procter & Gamble", null),
    ],
  },
  {
    id: "health-care",
    name: "Health Care",
    nameJa: "ヘルスケア",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLV",
    marketCapUsd: null,
    keywords: ["healthcare", "biotech", "GLP-1"],
    companies: [
      sectorCompany("LLY", "Eli Lilly", null),
      sectorCompany("UNH", "UnitedHealth", null),
      sectorCompany("JNJ", "Johnson & Johnson", null),
    ],
  },
  {
    id: "financials",
    name: "Financials",
    nameJa: "金融",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLF",
    marketCapUsd: null,
    keywords: ["banks", "capital markets", "insurance"],
    companies: [
      sectorCompany("JPM", "JPMorgan Chase", null),
      sectorCompany("BAC", "Bank of America", null),
      sectorCompany("GS", "Goldman Sachs", null),
    ],
  },
  {
    id: "industrials",
    name: "Industrials",
    nameJa: "資本財",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLI",
    marketCapUsd: null,
    keywords: ["industrial", "aerospace", "automation"],
    companies: [
      sectorCompany("GE", "GE Aerospace", null),
      sectorCompany("CAT", "Caterpillar", null),
      sectorCompany("ETN", "Eaton", null),
    ],
  },
  {
    id: "energy",
    name: "Energy",
    nameJa: "エネルギー",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLE",
    marketCapUsd: null,
    keywords: ["oil", "gas", "energy"],
    companies: [
      sectorCompany("XOM", "Exxon Mobil", null),
      sectorCompany("CVX", "Chevron", null),
      sectorCompany("SLB", "SLB", null),
    ],
  },
  {
    id: "materials",
    name: "Materials",
    nameJa: "素材",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLB",
    marketCapUsd: null,
    keywords: ["materials", "chemicals", "metals"],
    companies: [
      sectorCompany("LIN", "Linde", null),
      sectorCompany("SHW", "Sherwin-Williams", null),
      sectorCompany("FCX", "Freeport-McMoRan", null),
    ],
  },
  {
    id: "utilities",
    name: "Utilities",
    nameJa: "公益",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLU",
    marketCapUsd: null,
    keywords: ["utilities", "power demand", "grid"],
    companies: [
      sectorCompany("NEE", "NextEra Energy", null),
      sectorCompany("SO", "Southern Company", null),
      sectorCompany("CEG", "Constellation Energy", null),
    ],
  },
  {
    id: "real-estate",
    name: "Real Estate",
    nameJa: "不動産",
    displayMode: "sector",
    theme: "gics",
    benchmarkSymbol: "XLRE",
    marketCapUsd: null,
    keywords: ["REIT", "office", "real estate"],
    companies: [
      sectorCompany("PLD", "Prologis", null),
      sectorCompany("AMT", "American Tower", null),
      sectorCompany("EQIX", "Equinix", null),
    ],
  },
];
