import { sectorCompany } from "@/config/sector-momentum";
import type { SectorDefinition, SectorRegion } from "@/types/sector-momentum";

function intl(
  ticker: string,
  name: string,
  region: SectorRegion,
  countryCode: string,
  countryName: string,
  exchange: string,
  subcategory?: string,
) {
  return sectorCompany(ticker, name, null, {
    region,
    countryCode,
    countryName,
    exchange,
    subcategory,
  });
}

export const thematicDefinitions: SectorDefinition[] = [
  {
    id: "quantum-computing",
    name: "Quantum Computing",
    nameJa: "量子コンピューティング",
    displayMode: "theme",
    theme: "quantum-computing",
    benchmarkSymbol: "QTUM",
    marketCapUsd: null,
    keywords: ["quantum computing", "qubit", "quantum chip"],
    companies: [
      intl("IONQ", "IonQ", "us", "US", "United States", "NYSE"),
      intl("RGTI", "Rigetti Computing", "us", "US", "United States", "NASDAQ"),
      intl("QBTS", "D-Wave Quantum", "us", "US", "United States", "NYSE"),
      intl("IBM", "IBM", "us", "US", "United States", "NYSE"),
    ],
  },
  {
    id: "space-economy",
    name: "Space Economy",
    nameJa: "宇宙・宇宙開発",
    displayMode: "theme",
    theme: "space-economy",
    benchmarkSymbol: "UFO",
    marketCapUsd: null,
    keywords: ["space infrastructure", "satellite", "rocket launch"],
    companies: [
      intl("RKLB", "Rocket Lab", "us", "US", "United States", "NASDAQ"),
      intl("LUNR", "Intuitive Machines", "us", "US", "United States", "NASDAQ"),
      intl("PL", "Planet Labs", "us", "US", "United States", "NYSE"),
      intl("7011.T", "Mitsubishi Heavy Industries", "japan", "JP", "Japan", "TSE"),
      intl("7012.T", "Kawasaki Heavy Industries", "japan", "JP", "Japan", "TSE"),
    ],
  },
  {
    id: "ai-semiconductors",
    name: "AI Semiconductors",
    nameJa: "AI半導体",
    displayMode: "theme",
    theme: "ai-semiconductors",
    benchmarkSymbol: "SMH",
    marketCapUsd: null,
    keywords: ["GPU", "AI chip", "HBM"],
    companies: [
      intl("NVDA", "NVIDIA", "us", "US", "United States", "NASDAQ"),
      intl("AVGO", "Broadcom", "us", "US", "United States", "NASDAQ"),
      intl("AMD", "Advanced Micro Devices", "us", "US", "United States", "NASDAQ"),
      intl("TSM", "Taiwan Semiconductor", "taiwan", "TW", "Taiwan", "NYSE"),
      intl("2330.TW", "TSMC", "taiwan", "TW", "Taiwan", "TWSE"),
      intl("6857.T", "Advantest", "japan", "JP", "Japan", "TSE"),
      intl("8035.T", "Tokyo Electron", "japan", "JP", "Japan", "TSE"),
      intl("005930.KS", "Samsung Electronics", "korea", "KR", "South Korea", "KRX"),
    ],
  },
  {
    id: "ai-software",
    name: "AI Software & Models",
    nameJa: "AIソフトウェア/基盤モデル",
    displayMode: "theme",
    theme: "ai-software",
    benchmarkSymbol: "AIQ",
    marketCapUsd: null,
    keywords: ["foundation model", "AI software", "agentic AI"],
    companies: [
      intl("MSFT", "Microsoft", "us", "US", "United States", "NASDAQ"),
      intl("GOOGL", "Alphabet", "us", "US", "United States", "NASDAQ"),
      intl("PLTR", "Palantir", "us", "US", "United States", "NYSE"),
      intl("SNOW", "Snowflake", "us", "US", "United States", "NYSE"),
      intl("9984.T", "SoftBank Group", "japan", "JP", "Japan", "TSE"),
    ],
  },
  {
    id: "ai-infrastructure-theme",
    name: "AI Infrastructure & Data Centers",
    nameJa: "AIインフラ/データセンター",
    displayMode: "theme",
    theme: "ai-infrastructure",
    benchmarkSymbol: "DTCR",
    marketCapUsd: null,
    keywords: ["AI data center", "liquid cooling", "power density"],
    companies: [
      intl("EQIX", "Equinix", "us", "US", "United States", "NASDAQ"),
      intl("DLR", "Digital Realty", "us", "US", "United States", "NYSE"),
      intl("VRT", "Vertiv", "us", "US", "United States", "NYSE"),
      intl("ANET", "Arista Networks", "us", "US", "United States", "NYSE"),
      intl("9618.HK", "JD.com", "hong-kong", "HK", "Hong Kong", "HKEX"),
    ],
  },
  {
    id: "power-nuclear-theme",
    name: "Power & Nuclear",
    nameJa: "電力・原子力",
    displayMode: "theme",
    theme: "power-nuclear",
    benchmarkSymbol: "NLR",
    marketCapUsd: null,
    keywords: ["AI power demand", "nuclear", "grid"],
    companies: [
      intl("CEG", "Constellation Energy", "us", "US", "United States", "NASDAQ"),
      intl("VST", "Vistra", "us", "US", "United States", "NYSE"),
      intl("CCJ", "Cameco", "us", "CA", "Canada", "NYSE"),
      intl("SMR", "NuScale Power", "us", "US", "United States", "NYSE"),
      intl("9501.T", "Tokyo Electric Power", "japan", "JP", "Japan", "TSE"),
    ],
  },
  {
    id: "fusion",
    name: "Fusion Energy",
    nameJa: "核融合",
    displayMode: "theme",
    theme: "fusion",
    benchmarkSymbol: "NLR",
    marketCapUsd: null,
    keywords: ["fusion energy", "tokamak", "plasma"],
    companies: [
      intl("OKLO", "Oklo", "us", "US", "United States", "NYSE"),
      intl("6501.T", "Hitachi", "japan", "JP", "Japan", "TSE"),
      intl("7013.T", "IHI", "japan", "JP", "Japan", "TSE"),
    ],
  },
  {
    id: "robotics-humanoid",
    name: "Robotics & Humanoid",
    nameJa: "ロボティクス/ヒューマノイド",
    displayMode: "theme",
    theme: "robotics-humanoid",
    benchmarkSymbol: "BOTZ",
    marketCapUsd: null,
    keywords: ["humanoid robot", "factory automation", "robotics"],
    companies: [
      intl("ISRG", "Intuitive Surgical", "us", "US", "United States", "NASDAQ"),
      intl("SYM", "Symbotic", "us", "US", "United States", "NASDAQ"),
      intl("6861.T", "Keyence", "japan", "JP", "Japan", "TSE"),
      intl("6954.T", "Fanuc", "japan", "JP", "Japan", "TSE"),
    ],
  },
  {
    id: "autonomous-driving",
    name: "Autonomous Driving",
    nameJa: "自動運転",
    displayMode: "theme",
    theme: "autonomous-driving",
    benchmarkSymbol: "DRIV",
    marketCapUsd: null,
    keywords: ["autonomous driving", "robotaxi", "ADAS"],
    companies: [
      intl("TSLA", "Tesla", "us", "US", "United States", "NASDAQ"),
      intl("MBLY", "Mobileye", "us", "IL", "Israel", "NASDAQ"),
      intl("NVDA", "NVIDIA", "us", "US", "United States", "NASDAQ"),
      intl("7203.T", "Toyota Motor", "japan", "JP", "Japan", "TSE"),
    ],
  },
  {
    id: "cybersecurity-theme",
    name: "Cybersecurity",
    nameJa: "サイバーセキュリティ",
    displayMode: "theme",
    theme: "cybersecurity",
    benchmarkSymbol: "HACK",
    marketCapUsd: null,
    keywords: ["zero trust", "cloud security", "identity security"],
    companies: [
      intl("CRWD", "CrowdStrike", "us", "US", "United States", "NASDAQ"),
      intl("PANW", "Palo Alto Networks", "us", "US", "United States", "NASDAQ"),
      intl("ZS", "Zscaler", "us", "US", "United States", "NASDAQ"),
      intl("4704.T", "Trend Micro", "japan", "JP", "Japan", "TSE"),
    ],
  },
  {
    id: "defense",
    name: "Defense & Military Tech",
    nameJa: "防衛・軍需",
    displayMode: "theme",
    theme: "defense",
    benchmarkSymbol: "ITA",
    marketCapUsd: null,
    keywords: ["defense", "drone warfare", "missile defense"],
    companies: [
      intl("LMT", "Lockheed Martin", "us", "US", "United States", "NYSE"),
      intl("RTX", "RTX", "us", "US", "United States", "NYSE"),
      intl("NOC", "Northrop Grumman", "us", "US", "United States", "NYSE"),
      intl("7011.T", "Mitsubishi Heavy Industries", "japan", "JP", "Japan", "TSE"),
      intl("012450.KS", "Hanwha Aerospace", "korea", "KR", "South Korea", "KRX"),
    ],
  },
  {
    id: "biotech-genomics",
    name: "Biotech & Genomics",
    nameJa: "バイオテック/ゲノム",
    displayMode: "theme",
    theme: "biotech-genomics",
    benchmarkSymbol: "ARKG",
    marketCapUsd: null,
    keywords: ["genomics", "gene editing", "mRNA"],
    companies: [
      intl("MRNA", "Moderna", "us", "US", "United States", "NASDAQ"),
      intl("CRSP", "CRISPR Therapeutics", "us", "CH", "Switzerland", "NASDAQ"),
      intl("4568.T", "Daiichi Sankyo", "japan", "JP", "Japan", "TSE"),
      intl("4519.T", "Chugai Pharmaceutical", "japan", "JP", "Japan", "TSE"),
    ],
  },
  {
    id: "glp1-obesity",
    name: "GLP-1 & Obesity Drugs",
    nameJa: "肥満症治療薬(GLP-1)",
    displayMode: "theme",
    theme: "glp1-obesity",
    benchmarkSymbol: "PPH",
    marketCapUsd: null,
    keywords: ["GLP-1", "obesity drug", "diabetes"],
    companies: [
      intl("LLY", "Eli Lilly", "us", "US", "United States", "NYSE"),
      intl("NVO", "Novo Nordisk ADR", "europe", "DK", "Denmark", "NYSE"),
      intl("NOVO-B.CO", "Novo Nordisk", "europe", "DK", "Denmark", "Copenhagen"),
    ],
  },
  {
    id: "battery-storage",
    name: "Battery & Energy Storage",
    nameJa: "電池/エネルギー貯蔵",
    displayMode: "theme",
    theme: "battery-storage",
    benchmarkSymbol: "BATT",
    marketCapUsd: null,
    keywords: ["battery storage", "lithium", "grid storage"],
    companies: [
      intl("ALB", "Albemarle", "us", "US", "United States", "NYSE"),
      intl("6752.T", "Panasonic Holdings", "japan", "JP", "Japan", "TSE"),
      intl("373220.KS", "LG Energy Solution", "korea", "KR", "South Korea", "KRX"),
      intl("300750.SZ", "CATL", "china", "CN", "China", "SZSE"),
    ],
  },
  {
    id: "rare-earth-critical-minerals",
    name: "Rare Earth & Critical Minerals",
    nameJa: "レアアース/重要鉱物",
    displayMode: "theme",
    theme: "rare-earth-critical-minerals",
    benchmarkSymbol: "REMX",
    marketCapUsd: null,
    keywords: ["rare earth", "critical minerals", "copper"],
    companies: [
      intl("MP", "MP Materials", "us", "US", "United States", "NYSE"),
      intl("FCX", "Freeport-McMoRan", "us", "US", "United States", "NYSE"),
      intl("5713.T", "Sumitomo Metal Mining", "japan", "JP", "Japan", "TSE"),
      intl("2899.HK", "Zijin Mining", "hong-kong", "CN", "China", "HKEX"),
    ],
  },
  {
    id: "blockchain-crypto",
    name: "Blockchain & Crypto Equity",
    nameJa: "ブロックチェーン/暗号資産関連",
    displayMode: "theme",
    theme: "blockchain-crypto",
    benchmarkSymbol: "BLOK",
    marketCapUsd: null,
    keywords: ["blockchain", "bitcoin treasury", "crypto exchange"],
    companies: [
      intl("COIN", "Coinbase", "us", "US", "United States", "NASDAQ"),
      intl("MSTR", "MicroStrategy", "us", "US", "United States", "NASDAQ"),
      intl("MARA", "MARA Holdings", "us", "US", "United States", "NASDAQ"),
      intl("8473.T", "SBI Holdings", "japan", "JP", "Japan", "TSE"),
    ],
  },
  {
    id: "hbm-semicap",
    name: "HBM & Semiconductor Equipment / Materials",
    nameJa: "HBM・半導体製造装置・材料",
    displayMode: "theme",
    theme: "hbm-semicap",
    themeFamily: "pickaxe",
    benchmarkSymbol: "SMH",
    marketCapUsd: null,
    keywords: ["HBM", "semiconductor equipment", "advanced packaging", "wafer"],
    structureDescription:
      "AIチップの勝者を問わず、製造・検査・接続・材料の供給工程で需要を受ける川上バスケットです。",
    companies: [
      intl("RMBS", "Rambus", "us", "US", "United States", "NASDAQ", "インターフェースIP"),
      intl("LRCX", "Lam Research", "us", "US", "United States", "NASDAQ", "前工程装置"),
      intl("8035.T", "Tokyo Electron", "japan", "JP", "Japan", "TSE", "前工程装置"),
      intl("AMAT", "Applied Materials", "us", "US", "United States", "NASDAQ", "前工程装置"),
      intl("ASML", "ASML", "europe", "NL", "Netherlands", "NASDAQ", "前工程装置"),
      intl("BESI.AS", "BE Semiconductor Industries", "europe", "NL", "Netherlands", "Euronext Amsterdam", "後工程・ボンディング"),
      intl("KLAC", "KLA", "us", "US", "United States", "NASDAQ", "検査・計測"),
      intl("6920.T", "Lasertec", "japan", "JP", "Japan", "TSE", "検査・計測"),
      intl("6857.T", "Advantest", "japan", "JP", "Japan", "TSE", "検査・計測"),
      intl("TER", "Teradyne", "us", "US", "United States", "NASDAQ", "検査・計測"),
      intl("4063.T", "Shin-Etsu Chemical", "japan", "JP", "Japan", "TSE", "材料・基板・ウェハー"),
      intl("3436.T", "SUMCO", "japan", "JP", "Japan", "TSE", "材料・基板・ウェハー"),
      intl("6146.T", "DISCO", "japan", "JP", "Japan", "TSE", "材料・基板・ウェハー"),
      intl("4062.T", "Ibiden", "japan", "JP", "Japan", "TSE", "材料・基板・ウェハー"),
      intl("ENTG", "Entegris", "us", "US", "United States", "NASDAQ", "材料・基板・ウェハー"),
      intl("6266.T", "TAZMO", "japan", "JP", "Japan", "TSE", "材料・基板・ウェハー"),
    ],
  },
  {
    id: "ai-data-center-buildout",
    name: "AI Data Center Buildout",
    nameJa: "AIデータセンター建設",
    displayMode: "theme",
    theme: "ai-data-center-buildout",
    themeFamily: "pickaxe",
    benchmarkSymbol: "DTCR",
    marketCapUsd: null,
    keywords: ["data center construction", "power equipment", "liquid cooling", "fiber cable"],
    structureDescription:
      "どのAI企業が伸びても、計算設備を動かす電力・冷却・電線・建設・データセンター床の需要は発生します。",
    companies: [
      intl("ETN", "Eaton", "us", "US", "United States", "NYSE", "電力機器"),
      intl("SU.PA", "Schneider Electric", "europe", "FR", "France", "Euronext Paris", "電力機器"),
      intl("6501.T", "Hitachi", "japan", "JP", "Japan", "TSE", "電力・建設"),
      intl("GEV", "GE Vernova", "us", "US", "United States", "NYSE", "電力機器"),
      intl("7011.T", "Mitsubishi Heavy Industries", "japan", "JP", "Japan", "TSE", "発電設備"),
      intl("VRT", "Vertiv", "us", "US", "United States", "NYSE", "冷却・電源"),
      intl("6367.T", "Daikin Industries", "japan", "JP", "Japan", "TSE", "冷却"),
      intl("6273.T", "SMC", "japan", "JP", "Japan", "TSE", "空圧制御"),
      intl("PRY.MI", "Prysmian", "europe", "IT", "Italy", "Borsa Italiana", "電線"),
      intl("5801.T", "Furukawa Electric", "japan", "JP", "Japan", "TSE", "電線"),
      intl("5803.T", "Fujikura", "japan", "JP", "Japan", "TSE", "光ファイバー・電線"),
      intl("EQIX", "Equinix", "us", "US", "United States", "NASDAQ", "データセンターREIT"),
      intl("DLR", "Digital Realty", "us", "US", "United States", "NYSE", "データセンターREIT"),
    ],
  },
  {
    id: "ai-power-nuclear-picks",
    name: "AI Power & Nuclear Supply Chain",
    nameJa: "AI電力・原子力ツルハシ",
    displayMode: "theme",
    theme: "ai-power-nuclear-picks",
    themeFamily: "pickaxe",
    benchmarkSymbol: "NLR",
    marketCapUsd: null,
    keywords: ["uranium", "SMR", "nuclear operator", "gas turbine"],
    structureDescription:
      "AI電力需要を、燃料・小型炉・原発運営・タービンという供給網側から観測するテーマです。",
    companies: [
      intl("CCJ", "Cameco", "us", "CA", "Canada", "NYSE", "ウラン"),
      intl("SMR", "NuScale Power", "us", "US", "United States", "NYSE", "SMR"),
      intl("BWXT", "BWX Technologies", "us", "US", "United States", "NYSE", "原子炉部品"),
      intl("CEG", "Constellation Energy", "us", "US", "United States", "NASDAQ", "原発運営"),
      intl("ENR.DE", "Siemens Energy", "europe", "DE", "Germany", "XETRA", "ガスタービン・送電"),
    ],
  },
  {
    id: "robotics-components",
    name: "Robotics & Automation Components",
    nameJa: "ロボット・自動化部品",
    displayMode: "theme",
    theme: "robotics-components",
    themeFamily: "pickaxe",
    benchmarkSymbol: "BOTZ",
    marketCapUsd: null,
    keywords: ["reducer", "servo motor", "machine vision", "factory sensor"],
    structureDescription:
      "ロボット本体ではなく、減速機・サーボ・センサー・画像認識など自動化に不可欠な部品を追います。",
    companies: [
      intl("6324.T", "Harmonic Drive Systems", "japan", "JP", "Japan", "TSE", "減速機"),
      intl("6268.T", "Nabtesco", "japan", "JP", "Japan", "TSE", "減速機"),
      intl("6506.T", "Yaskawa Electric", "japan", "JP", "Japan", "TSE", "サーボ"),
      intl("6954.T", "Fanuc", "japan", "JP", "Japan", "TSE", "FA制御"),
      intl("6861.T", "Keyence", "japan", "JP", "Japan", "TSE", "センサー"),
      intl("CGNX", "Cognex", "us", "US", "United States", "NASDAQ", "マシンビジョン"),
      intl("6645.T", "Omron", "japan", "JP", "Japan", "TSE", "制御・センサー"),
    ],
  },
  {
    id: "space-infrastructure",
    name: "Space Infrastructure & Components",
    nameJa: "宇宙インフラ・部品",
    displayMode: "theme",
    theme: "space-infrastructure",
    themeFamily: "pickaxe",
    benchmarkSymbol: "UFO",
    marketCapUsd: null,
    keywords: ["launch services", "satellite components", "earth observation"],
    structureDescription:
      "打ち上げ、衛星部品、観測データなど、宇宙サービスの基盤となる供給側を追跡します。",
    companies: [
      intl("RKLB", "Rocket Lab", "us", "US", "United States", "NASDAQ", "打ち上げ"),
      intl("6503.T", "Mitsubishi Electric", "japan", "JP", "Japan", "TSE", "衛星部品"),
      intl("PL", "Planet Labs", "us", "US", "United States", "NYSE", "データ解析"),
      intl("BKSY", "BlackSky Technology", "us", "US", "United States", "NYSE", "データ解析"),
    ],
  },
  {
    id: "ev-battery-supply-chain",
    name: "EV & Battery Equipment / Materials",
    nameJa: "EV・電池製造装置・材料",
    displayMode: "theme",
    theme: "ev-battery-supply-chain",
    themeFamily: "pickaxe",
    benchmarkSymbol: "BATT",
    marketCapUsd: null,
    keywords: ["battery separator", "lithium", "battery testing"],
    structureDescription:
      "EV完成車ではなく、電池の製造装置・セパレーター・リチウムなど供給網の構造データを見ます。",
    companies: [
      intl("3407.T", "Asahi Kasei", "japan", "JP", "Japan", "TSE", "セパレーター"),
      intl("3402.T", "Toray Industries", "japan", "JP", "Japan", "TSE", "材料"),
      intl("ALB", "Albemarle", "us", "US", "United States", "NYSE", "リチウム"),
      intl("SQM", "Sociedad Quimica y Minera", "us", "CL", "Chile", "NYSE", "リチウム"),
      intl("6866.T", "Hioki E.E.", "japan", "JP", "Japan", "TSE", "電池検査"),
    ],
  },
  {
    id: "drug-discovery-cdmo",
    name: "Drug Discovery Tools & CDMO",
    nameJa: "創薬支援・CDMO",
    displayMode: "theme",
    theme: "drug-discovery-cdmo",
    themeFamily: "pickaxe",
    benchmarkSymbol: "IHE",
    marketCapUsd: null,
    keywords: ["CDMO", "life science tools", "GLP-1 manufacturing"],
    structureDescription:
      "新薬の成否とは別に、研究装置・分析・受託製造・投薬機器を供給する周辺企業をまとめます。",
    companies: [
      intl("TMO", "Thermo Fisher Scientific", "us", "US", "United States", "NYSE", "研究装置"),
      intl("DHR", "Danaher", "us", "US", "United States", "NYSE", "研究装置"),
      intl("7701.T", "Shimadzu", "japan", "JP", "Japan", "TSE", "分析装置"),
      intl("LONN.SW", "Lonza", "europe", "CH", "Switzerland", "SIX", "CDMO"),
      intl("207940.KS", "Samsung Biologics", "korea", "KR", "South Korea", "KRX", "CDMO"),
      intl("4543.T", "Terumo", "japan", "JP", "Japan", "TSE", "投薬機器"),
      intl("8086.T", "Nipro", "japan", "JP", "Japan", "TSE", "投薬機器"),
    ],
  },
  {
    id: "defense-electronics",
    name: "Defense Electronics",
    nameJa: "防衛エレクトロニクス",
    displayMode: "theme",
    theme: "defense-electronics",
    themeFamily: "pickaxe",
    benchmarkSymbol: "ITA",
    marketCapUsd: null,
    keywords: ["electronic warfare", "secure communications", "defense sensor"],
    structureDescription:
      "完成兵器ではなく、センサー・通信・電子戦など防衛システムの中核部品を供給する企業群です。",
    companies: [
      intl("LHX", "L3Harris Technologies", "us", "US", "United States", "NYSE", "通信・電子戦"),
      intl("6503.T", "Mitsubishi Electric", "japan", "JP", "Japan", "TSE", "センサー・通信"),
      intl("LDO.MI", "Leonardo", "europe", "IT", "Italy", "Borsa Italiana", "防衛電子機器"),
    ],
  },
  {
    id: "ai-software-security",
    name: "AI Software Infrastructure & Security",
    nameJa: "AIソフト基盤・セキュリティ",
    displayMode: "theme",
    theme: "ai-software-security",
    themeFamily: "pickaxe",
    benchmarkSymbol: "HACK",
    marketCapUsd: null,
    keywords: ["observability", "data platform", "cloud security", "zero trust"],
    structureDescription:
      "AI利用を支える監視・データ基盤・セキュリティを、アプリ層のインフラとして追跡します。",
    companies: [
      intl("DDOG", "Datadog", "us", "US", "United States", "NASDAQ", "監視"),
      intl("CRWD", "CrowdStrike", "us", "US", "United States", "NASDAQ", "サイバー"),
      intl("PANW", "Palo Alto Networks", "us", "US", "United States", "NASDAQ", "サイバー"),
      intl("NET", "Cloudflare", "us", "US", "United States", "NYSE", "ネットワーク基盤"),
    ],
  },
  {
    id: "crypto-infrastructure",
    name: "Crypto Infrastructure",
    nameJa: "暗号資産インフラ",
    displayMode: "theme",
    theme: "crypto-infrastructure",
    themeFamily: "pickaxe",
    benchmarkSymbol: "BLOK",
    marketCapUsd: null,
    keywords: ["crypto exchange", "custody", "stablecoin"],
    structureDescription:
      "暗号資産価格そのものではなく、取引所・カストディ・ステーブルコインの取引基盤を観測します。",
    companies: [
      intl("COIN", "Coinbase", "us", "US", "United States", "NASDAQ", "取引所・カストディ"),
      intl("CRCL", "Circle Internet Group", "us", "US", "United States", "NYSE", "ステーブルコイン"),
    ],
  },
];
